ALTER TABLE users
ADD COLUMN email VARCHAR(255) UNIQUE,
ADD COLUMN google_id VARCHAR(255) UNIQUE,
ADD COLUMN first_name VARCHAR(255),
ADD COLUMN last_name VARCHAR(255),
ADD COLUMN avatar_url VARCHAR(1024);
